### ISSUE TITLE
Адаптивность

### ISSUE THREAD

**Issue by HeyRoach** [Axent13/intern-maket-2#1]
от 1240 и меньше в хэдере и в футере всё плохо)

**Comment by HeyRoach** [comment]
еще и кнопка know more поехала

**Comment by Axent13** [comment]
А что именно там плохо?) Я просто решил по центру все сделать, макета же для маленьких экранов все равно нет)
![iss1](https://cloud.githubusercontent.com/assets/5270902/18950697/50887780-866b-11e6-8495-1d0b9751b0c7.png)

А как нужно чтобы выглядело?

**Comment by HeyRoach** [comment]
Конечно, если нет макета на другие размеры, каждый адаптирует так, как считает нужным. Просто в данном случае на большом экране кнопка не центрируется, как и элементы в хедере. Почему бы не соблюдать единообразие? Особенно если ширина экрана позволяет не лепить элементы хедера друг на друга, а сделать так, как это выглядит на большом экране. Как считаешь?
