### ISSUE TITLE
Телефон и линии

### ISSUE THREAD

**Issue by HeyRoach** [Axent13/intern-maket-2#3]
по поводу зеленых линий - подход лучше - это сделать их не div, а  after

**Comment by Axent13** [comment]
Не совсем понял, что имеешь ввиду.)
Т.е. мне надо убрать эти два div'а - top-line и bottom-line, и "перенести" их в ::after каких-нибудь других тегов?
![after](https://cloud.githubusercontent.com/assets/5270902/19410256/66101182-9311-11e6-85f9-c0e28e58f697.png)

**Comment by HeyRoach** [comment]
Да)
